travis:
  secure:
    BINSTAR_TOKEN: hvd7rlbVMS5/EzL6Qvun83q2ZyCEmbfMkrljqvttry+xyMqQdH6y6DVUVa5IQPdF1smx/jMqcS0IN5hgoI6YOmg8eWiY/r64UBjiErB42GGeBzrCh/G0mRwuQPXAppcAPOUDZflpibkqmPQrs6/jfxSZfUtarHaelgf4Tc7Ko0OCE9/SMGWL28WRUBNacAyChWhgrVgsXI1UzQXx+Qb6N7Q8KTXVp0h+cisbPok+kFb11S6HBtAd72PVfc2/0Vs3zOvPz5aC0zI3ycJm1/x3ROO0MWOhwMOqBglVIai+R56nUuma5yG5gZ/UBgbmA1i43BVGkSKAaDJ9gDuul6rJ4C4sw3G4YMpGkC5Z/lESBDUELRDWajwj0EeDV5N/GdanxOQo8m9klI4G8EDEEY0xT4jO/r3ow+kIjTDov4tY9eEAzAW1DmRX62os1Jgb9SJKx6jnaGBDONERAT+5U+PJXFgrWbRbyxsf/hWnCUaXv6Yi/KTFDH8MhkeYkOVqTVAR/VNA0O1WO3RyAichFIMinrEXB8HWIgTLG7iqCAueTKPiUjQlCXH3v8mWl9riE8cSUVlCzHpkUtxfdX0u3gWHr6raF5jKR73hSb0RgdaPKTSiFevKnLfr4YJ5qJqP78dI3n8owAEEoMbfX353ZwVRizK1ZNGMla3VokfSJOBaeH4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
